In [9]:
import numpy as np
x = np.array([3,5,78,93])
array = np.less(x, 5)
array
#np.count_nonzero(array == True)

array([ True, False, False, False])

In [11]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(4,5))
x

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [15]:
x < 6


array([[ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])

In [21]:
np.less(x, 6)
np.sum(x)
x

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [23]:
np.add.accumulate(x)

array([[ 5,  0,  3,  3,  7],
       [14,  3,  8,  5, 11],
       [21,  9, 16, 13, 12],
       [27, 16, 23, 21, 13]])

In [24]:
x

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1]])

In [28]:
np.add.accumulate(x[x < 7])

array([ 5,  5,  8, 11, 14, 19, 21, 25, 31, 32, 38, 39])

In [37]:
x = np.arange(20)
print(x)
x[(x>4) and (x <10)]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()