In [2]:
array = list(range(200))
array

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [3]:
array

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [5]:
import numpy as np
array = np.random.randint(30, size=20)
array

array([28,  7, 13,  3, 27,  4,  6, 24, 11, 28,  3, 23, 24,  5,  6, 17, 19,
       16, 27,  5])

In [11]:
array[5:10]
array[1:10:2]

array([ 7,  3,  4, 24, 28])

In [12]:
array[::-1]

array([ 5, 27, 16, 19, 17,  6,  5, 24, 23,  3, 28, 11, 24,  6,  4, 27,  3,
       13,  7, 28])

In [16]:
array = list(range(10))
print(array)
array[4::-2]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[4, 2, 0]

In [17]:
array2 = np.random.randint(100, size=(5,5))
array2

array([[68, 86, 18, 85, 47],
       [38, 22, 33, 49, 84],
       [49,  9, 15, 75, 25],
       [60, 86, 99, 78, 86],
       [70, 25, 56, 19, 78]])

In [21]:
array2[1:4, 1:4]

array([[22, 33, 49],
       [ 9, 15, 75],
       [86, 99, 78]])

In [22]:
array2[::-1, ::-1]

array([[78, 19, 56, 25, 70],
       [86, 78, 99, 86, 60],
       [25, 75, 15,  9, 49],
       [84, 49, 33, 22, 38],
       [47, 85, 18, 86, 68]])

In [24]:
array2[::, 0 ]

array([68, 38, 49, 60, 70])

In [30]:
grilla = np.arange(1,10).reshape((3,3))
grilla

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr1 = np.random.randint(20, size=(3,4))
arr2 = np.random.randint(30, size=(3,4))
print(arr1)
print(arr2)
np.concatenate([arr1, arr2])

[[12 16  4 11]
 [11  6  1  0]
 [ 9  2 16 15]]
[[ 7  6 13  1 14]
 [16 11 23 28 12]
 [24  4 14  0  6]
 [20 29 29 18 22]
 [24 21  2  1 23]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 5

In [45]:
x = np.arange(81).reshape((9,9))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [46]:
2**x

array([[                   1,                    2,                    4,
                           8,                   16,                   32,
                          64,                  128,                  256],
       [                 512,                 1024,                 2048,
                        4096,                 8192,                16384,
                       32768,                65536,               131072],
       [              262144,               524288,              1048576,
                     2097152,              4194304,              8388608,
                    16777216,             33554432,             67108864],
       [           134217728,            268435456,            536870912,
                  1073741824,           2147483648,           4294967296,
                  8589934592,          17179869184,          34359738368],
       [         68719476736,         137438953472,         274877906944,
                549755813888,     

In [54]:
x = np.array([-2,-5, 6,9,3])
print(x)
abs(x)

[-2 -5  6  9  3]


array([2, 5, 6, 9, 3])

In [55]:
x = np.arange(15)
y = np.empty(15)
np.multiply(x, 10, out=y)
y

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.,
       110., 120., 130., 140.])

In [63]:
x = np.arange(1,6)
print(x)
np.multiply.accumulate(x)

[1 2 3 4 5]


array([  1,   2,   6,  24, 120])