In [6]:
import numpy as np
arr = np.array([435,'a',7,8,99,True])
arr
arr2 = np.arange(10)
print(arr2)
arr2

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
boolean_array = np.full((3,3), True,dtype=bool)
boolean_array
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
arr = np.array([6,8,6,2,4,5,1,0,3])
arr[1::2]

arr[arr % 2 == 0]

array([6, 8, 6, 2, 4, 0])

In [20]:
arr = np.arange(20)
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

In [25]:
arr = np.random.randint(0,40, size=10)
out = arr.copy()
out = np.where(arr%2==1, -1,arr)
arr, out


(array([37,  1,  4,  0,  1,  1, 33,  9, 29, 21]),
 array([-1, -1,  4,  0, -1, -1, -1, -1, -1, -1]))

In [31]:
arr = np.arange(10)
arr.reshape((2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
a = np.arange(10).reshape(2,5)
b= np.repeat(1,10).reshape(2,-1)
a,b
np.concatenate([a,b], axis=0)
np.vstack((a,b))
np.concatenate((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])