In [1]:
import numpy as np

In [2]:
np.array([1,2,3,6,3,7])

array([1, 2, 3, 6, 3, 7])

In [3]:
_[1:2]

array([2])

In [4]:
np.array([23,5,6,7.5])

array([23. ,  5. ,  6. ,  7.5])

In [7]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:

x1 = np.random.randint(10, size=6)
x1

array([3, 5, 2, 4, 7, 6])